# GitHub Action para gerar a animação da cobra de contribuições

name: Generate Snake Animation

on:
  # Executa automaticamente a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  
  # Permite executar esta action manualmente a partir do separador Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          # O seu nome de utilizador do GitHub
          github_user_name: rootunk
          
          # Lista de outputs que devem ser gerados
          # O ficheiro de animação será guardado em "dist/github-contribution-grid-snake.svg"
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          # O diretório que contém os ficheiros a serem publicados
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
